### PR TITLE
AMD64 assembler functions

### PR DESCRIPTION
**Pull request by klauspost**
Recreated the PR #3, since it got a bit to messy after rebase.

Adds SSE2 assembler for the following operations:
- Mul / Add / Rcp / Sqrt / Min / Max / AddConst / Scale

### CODE REVIEW

**Comment by klauspost** [comment]
Rebased, and added "AddScaled", "Sum", "Abs".

**Comment by leoneu** [comment]
Hi Klaus, I started to look at your work. I haven't done anything with assembler in Go, I think we will need extensive unit tests to make sure there are no issues. I'm trying to decide if it makes sense to do merge your code and understand what the downside might be. I saw this old project https://github.com/ziutek/blas which seems to do something similar, have you looked at it? Anyway, I will try to run some tests tomorrow.

**Comment by klauspost** [comment]
Good things to test:
- [ ] Are all elements done correctly? - especially the last few elements are important to test. Hence #4 
- [ ] Check with different sizes, especially sizes that aren't multiple of 4, 8 or 16.
- [ ] Does it touch elements that it shouldn't (easily tested, by re-slicing the array, and checking thwe original).
- [ ] Does it accidentally alter input slices?

In other projects, I have used [gofuzz](https://github.com/google/gofuzz) for fuzz testing, which is easy and good. You could consider that.

**Comment by leoneu** [comment]
Merged. Added more tests, we can exclude functions from being generated. The best candidates for assembler I think are Log and Exp, I think.

**Pull request merged**
